# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-06 20:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CancelledEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_from', models.DateField(db_index=True, verbose_name='Valid from')),
                ('valid_until', models.DateField(db_index=True, verbose_name='Valid until')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Cancelled event',
                'verbose_name_plural': 'Cancelled events',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('valid_from', models.DateField(db_index=True, verbose_name='Valid from')),
                ('start', models.TimeField(verbose_name='Start')),
                ('stop', models.TimeField(blank=True, null=True, verbose_name='Stop')),
                ('repeat', models.IntegerField(blank=True, choices=[(1, 'Do not repeat'), (2, 'Daily'), (3, 'Weekly'), (4, 'Bi-weekly'), (5, 'Monthly'), (6, 'Yearly')], null=True, verbose_name='Repeat')),
                ('valid_until', models.DateField(blank=True, db_index=True, null=True, verbose_name='Valid until')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduler.Category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'event',
                'verbose_name_plural': 'events',
            },
        ),
        migrations.AddField(
            model_name='cancelledevent',
            name='events',
            field=models.ManyToManyField(related_name='cancelled', to='scheduler.Event', verbose_name='Events'),
        ),
    ]
